
name: 'Terraform deploy'
  

on:
  push:
    branches:
      - main

jobs:
  deploy_storage_s3:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup terraform cli
        uses: hashicorp/setup-terraform@v2

      - name: terraform init and plan
        run: |
            cd stage/storage/s3
            terraform init
            terraform plan -out terraform.tfplan

      - name: terraform apply
        run: terraform apply terraform.tfplan -auto-approve
